# Generated by Django 5.0.3 on 2024-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='silver90', max_length=20, verbose_name={'gold180': 'Gold180', 'platitnum365': 'Platinum365', 'silver90': 'Silver90'})),
                ('cost', models.IntegerField(default='199', max_length=10, verbose_name={'199': 199, '299': 299, '499': 499})),
                ('validity', models.IntegerField(default='90_days', max_length=10, verbose_name={'180_days': 180, '365_days': 365, '90_days': 90})),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['id'],
                'default_related_name': 'plans',
            },
        ),
    ]
